AWSTemplateFormatVersion: '2010-09-09'

Description: Creates a budget with configurable limit and notification.

Parameters:

  BudgetLimit:
    Type: Number  
    Default: 5
    Description: The total budgeted amount

  NotificationEmail:
    Type: String
    Description: Email address to notify if actual costs exceed budgeted costs
      
Resources:

  MonthlyBudget: 
    Type: AWS::Budgets::Budget
    Properties:
      Budget: 
        BudgetLimit: !Ref BudgetLimit
        BudgetName: MonthlyBudget
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail